name: Ultraviolet-Node
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs the specified commands commands to get Ultraviolet-Node running.
      - name: run ultraviolet
        run: |
          git clone https://github.com/IDontCodee/Tsunami
          cd Tsunami
          npm install
          screen -dm npm start
      - name: tunnel and expose to web
        run: |
          npm install -g localtunnel
          yarn add localtunnel
          sleep 1
          "lt -p 8080"
          sleep 1
          tmux capture-pane -pt uv -S 1 -E 1
      - name: sleep
        run: sleep 999999999
